### ISSUE TITLE
Turn it into a Spin component

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin-redirect#2]
It's currently WAGI; for now I'm doing minimal change, but it would be nice to make it fully Spin.

**Comment by vdice** [comment]
Implemented in https://github.com/fermyon/spin-redirect/pull/6.

We should call out this change in the next release; users will need to update their usage (eg remove `executor = { type = "wagi" }`)

**Comment by itowlson** [comment]
@vdice is that going to mean a template change too

**Comment by vdice** [comment]
@itowlson Ah, thank you, yes!  Shall I create an issue in spin for this?  _edit: Er, perhaps in this repo since we'll be in charge of the actual release._

**Comment by itowlson** [comment]
Thanks - yeah not sure the best place to record the issue - the change needs to be at the same time as we switch the Spin template over to the new redirect version - maybe an issue in the Spin repo to update template to point to the new release when available, and we could capture the executor thing there?  Not sure sorry
